os: osx
osx_image: xcode10.1
language: swift

cache:
  directories:
  - Carthage

before_install:
  - brew install carthage

script:
  - bundle exec fastlane tests

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'GetStream-iOS'
